// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsFpuFfyYuZQj3ahHoTEtXynTZJnIRrSk',
    appId: '1:46116775451:web:b06eb9343782ec2298fabe',
    messagingSenderId: '46116775451',
    projectId: 'flutterchatapp-a1a92',
    authDomain: 'flutterchatapp-a1a92.firebaseapp.com',
    storageBucket: 'flutterchatapp-a1a92.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOedz4uGPnkE0u_hzZ8z6-yqAPkZDsUdg',
    appId: '1:46116775451:android:f5e9817078dc7a7e98fabe',
    messagingSenderId: '46116775451',
    projectId: 'flutterchatapp-a1a92',
    storageBucket: 'flutterchatapp-a1a92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0opYXx4U0RBb9tFeqOF8FQ_pfmC2MSd8',
    appId: '1:46116775451:ios:285bfaebeb0a6de698fabe',
    messagingSenderId: '46116775451',
    projectId: 'flutterchatapp-a1a92',
    storageBucket: 'flutterchatapp-a1a92.appspot.com',
    iosClientId: '46116775451-tv4imb63852796pa6j7ves0ps2ci5utf.apps.googleusercontent.com',
    iosBundleId: 'com.xajxatel.bitsconfess.bitsconfess',
  );
}
